[project]
name = "3xpl-mcp"
version = "0.1.0"
description = "MCP server for interacting with 48 blockchains via 3xpl JSON API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
]
